<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VD4OOGI" failures="0" tests="5" name="com_scm_Practice_TESTNG.Basic_TESTNG_TEST1" time="0.009" errors="1" timestamp="2023-10-20T06:30:31 IST" skipped="0">
  <testcase classname="com_scm_Practice_TESTNG.Basic_TESTNG_TEST1" name="DeleteData" time="0.001"/>
  <system-out/>
  <testcase classname="com_scm_Practice_TESTNG.Basic_TESTNG_TEST1" name="DeleteData" time="0.000"/>
  <system-out/>
  <testcase classname="com_scm_Practice_TESTNG.Basic_TESTNG_TEST1" name="EditData" time="0.001">
    <error message="Index 6 out of bounds for length 4" type="java.lang.ArrayIndexOutOfBoundsException">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 4
at com_scm_Practice_TESTNG.Basic_TESTNG_TEST1.EditData(Basic_TESTNG_TEST1.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- EditData -->
  <system-out/>
  <testcase classname="com_scm_Practice_TESTNG.Basic_TESTNG_TEST1" name="DeleteData" time="0.006"/>
  <system-out/>
  <testcase classname="com_scm_Practice_TESTNG.Basic_TESTNG_TEST1" name="createdata" time="0.001"/>
  <system-out/>
</testsuite> <!-- com_scm_Practice_TESTNG.Basic_TESTNG_TEST1 -->
